name: BSPRandomTeleport
version: 1.1.1
main: eu.blackspectrum.randomteleport.RandomTeleport
depend: [MassiveCore, Factions]
commands:
  randomteleportreload:
    description: Reloads the Random Teleport config files.
    usage: /rtpreload
    permission: rtp.commands
    permission-message: You do not have permission to use this command.
    aliases: [randomtpreload, rtpreload]
  randomteleport:
    description: Random teleports a player.
    usage: /rtp or /rtp <player>
    permission: rtp.commands
    permission-message: You do not have permission to use this command.
    aliases: [randomtp, rtp]
permissions:
  rtp.commands:
    default: op